name: BuildTool
version: '${project.version}'
main: azuazu3939.buildtool.BuildTool
api-version: 1.15

commands:
  BuildTool:
    permission: BuildTool.command.BuildTool
    description: "建築仕様。"

permissions:
  BuildTool.command.BuildTool:
    default: false
  BuildTool.use.BuildTool:
    default: true